### ISSUE TITLE
Question about function read() of Class STM32Hardware

### ISSUE THREAD

**Issue by wangjiefjj** [yoneken/rosserial_stm32#5]
thank you for your sharing!
I try to transplant this code to F4,  I can not understand how the function read()  get data from Uart, your code just Receive data one time in function  init(), does the function init() run more than one time and is there any other function which can Receive data from Uart?

**Comment by yoneken** [comment]
Hi! Thank you for your comment!!
In this project, [I use DMA (Direct Memory Access) feature of STM32](https://github.com/yoneken/rosserial_stm32/blob/master/src/ros_lib/examples/chatter/chatter.ioc#L5-L13).
Thanks to the feature, received USART data is automatically reserved to the memory.
