### ISSUE TITLE
 Hello, tell me how you set up the UART and the timer in the STM32cubemx?

### ISSUE THREAD

**Issue by ivliev123** [yoneken/rosserial_stm32#7]

**Comment by ivliev123** [comment]
Hello, tell me how you set up the UART and the timer in the STM32cubemx

**Comment by yoneken** [comment]
This question is not related in this repo.
Each ioc file in the examples (i.e. [chatter.ioc](https://github.com/yoneken/rosserial_stm32/blob/master/src/ros_lib/examples/chatter/chatter.ioc) ) may help you.
